version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.django.rule=Host(`api.sagaryadav.dev`)" # Replace with your domain
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  pihole:
    image: pihole/pihole
    environment:
      - TZ=Asia/Kolkata # Set your desired timezone
      - WEBPASSWORD=admin # Set your desired Pi-hole web interface password
      - DNS1=1.1.1.1 # Set your desired DNS servers
      - DNS2=1.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8082:80" # Expose Pi-hole web interface on port 8082
    volumes:
      - "./pihole/pihole:/etc/pihole"
      - "./pihole/dnsmasq.d:/etc/dnsmasq.d"

  traefik:
    image: traefik:latest
    command:
      - "--configFile=/etc/traefik/traefik.yml" # Path to your traefik.yml file
    ports:
      - "80:80" # Expose port 80 for HTTP challenges
      - "443:443" # Expose port 443 for HTTPS traffic
      - "8080:8080" # Expose Traefik dashboard on port 8080
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Mount the traefik.yml file
      - "./letsencrypt:/etc/letsencrypt" # Mount the Let's Encrypt certificates directory
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount Docker socket for communication with Docker API
      - "/var/log/traefik:/var/log/traefik" # Mount the log directory
    depends_on:
      - web
