version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    labels:
      - "traefik.enable=true" # Enable Traefik for this service
      - "traefik.http.routers.django.rule=Host(`api.sagaryadav.dev`)" # Replace with your domain
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  adguard:
    image: adguard/adguardhome:latest
    ports:
      - "1234:53/tcp"
      - "1234:53/udp"
      - "6767:67/udp"
      - "6868:68/udp"
      - "853:853/tcp"
      - "3000:3000"
    volumes:
      - "./adguard/work:/opt/adguardhome/work"
      - "./adguard/conf:/opt/adguardhome/conf"
      - "./adguard/logs:/opt/adguardhome/logs"
    restart: always

  traefik:
    image: traefik:latest
    command:
      - "--configFile=/etc/traefeik/traefik.yml" # Path to your traefik.yml file
    ports:
      - "80:80" # Expose port 80 for HTTP challenges
      - "443:443" # Expose port 443 for HTTPS traffic
      - "8080:8080" # Expose Traefik dashboard on port 8080
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro" # Mount the traefik.yml file
      - "./letsencrypt:/etc/letsencrypt" # Mount the Let's Encrypt certificates directory
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount Docker socket for communication with Docker API
      - "/var/log/traefik:/var/log/traefik" # Mount the log directory
    depends_on:
      - web
